-- Fortify App — Seed Data
-- Run this AFTER 001_initial.sql against your Supabase project

-- ============================================================
-- MOVEMENT LIBRARY (40+ rows)
-- ============================================================
insert into movements (id, name, category, subcategory, tags, youtube_url, youtube_embed_id, cue_points, description, difficulty, equipment, primary_muscles, secondary_muscles) values
('back_squat','Back Squat','squat','bilateral','{posterior_chain,crossfit,athx,bilateral,barbell}','https://www.youtube.com/watch?v=ultWZbUMPL8','ultWZbUMPL8',ARRAY['Bar on traps not neck','Break hips and knees simultaneously','Knees track over toes','Drive floor away on ascent'],'The foundational bilateral squat. Primary strength builder for CrossFit and ATHX athletes.','beginner',ARRAY['barbell','rack'],ARRAY['quadriceps','glutes'],ARRAY['hamstrings','core','upper_back']),
('front_squat','Front Squat','squat','front_loaded','{posterior_chain,crossfit,olympic,bilateral,barbell}','https://www.youtube.com/watch?v=m4ytaCJZpl0','m4ytaCJZpl0',ARRAY['Elbows high fingertip grip or crossed','Torso stays vertical','Knees forward over toes','Breathe and brace before descent'],'More upright torso than back squat. Directly transfers to the clean and thruster.','intermediate',ARRAY['barbell','rack'],ARRAY['quadriceps','glutes'],ARRAY['core','upper_back','hamstrings']),
('goblet_squat','Goblet Squat','squat','front_loaded','{crossfit,hyrox,beginner_friendly,kettlebell,dumbbell}','https://www.youtube.com/watch?v=MeIiIdhvXT4','MeIiIdhvXT4',ARRAY['Hold weight at chest','Elbows inside knees at bottom','Sit tall do not collapse forward','Drive heels through floor'],'Excellent teaching tool for squat mechanics. Used as warm-up or accessory loading.','beginner',ARRAY['kettlebell','dumbbell'],ARRAY['quadriceps','glutes'],ARRAY['core','adductors']),
('bulgarian_split_squat','Bulgarian Split Squat','squat','unilateral','{posterior_chain,hyrox,athx,unilateral,single_leg,dumbbell,barbell}','https://www.youtube.com/watch?v=2C-uNgKwPLE','2C-uNgKwPLE',ARRAY['Rear foot elevated on bench or box','Front shin stays vertical','Drive through front heel','2-second controlled descent'],'The single most effective unilateral lower body movement for sport. Builds hip drive and running strength.','intermediate',ARRAY['dumbbell','barbell','bench'],ARRAY['quadriceps','glutes'],ARRAY['hamstrings','core','hip_flexors']),
('pause_squat','Pause Squat','squat','pause','{crossfit,athx,bilateral,barbell,strength}','https://www.youtube.com/watch?v=Dy5jCBLB4XY','Dy5jCBLB4XY',ARRAY['2-3 second pause at bottom','Stay braced through the pause','Do not relax glutes at bottom','Explode on the way up'],'Eliminates the stretch-shortening cycle. Builds pure bottom-position strength.','intermediate',ARRAY['barbell','rack'],ARRAY['quadriceps','glutes'],ARRAY['hamstrings','core']),
('safety_bar_squat','Safety Bar Squat','squat','bilateral','{hyrox,posterior_chain,safety_bar,bilateral}','https://www.youtube.com/watch?v=Zo6TGnhMmAE','Zo6TGnhMmAE',ARRAY['Handles at chest elbows up','More upright torso than back squat','Drive hips back on descent','Shifts load to quads and upper back'],'Allows heavy squatting with reduced shoulder and wrist demands.','intermediate',ARRAY['safety_bar','rack'],ARRAY['quadriceps','glutes'],ARRAY['upper_back','core','hamstrings']),
('step_up','Step-Up','squat','unilateral','{hyrox,running_economy,dumbbell,unilateral,single_leg}','https://www.youtube.com/watch?v=dQqApCGd5Ss','dQqApCGd5Ss',ARRAY['Drive through heel of working leg','Do not push off back foot','Control descent','Full hip extension at top'],'Builds single-leg quad and glute strength. Important for Hyrox running economy.','beginner',ARRAY['dumbbell','box'],ARRAY['quadriceps','glutes'],ARRAY['hamstrings','core']),
('conventional_deadlift','Conventional Deadlift','hinge','conventional','{posterior_chain,athx,hyrox,bilateral,barbell,strength}','https://www.youtube.com/watch?v=op9kVnSso6Q','op9kVnSso6Q',ARRAY['Hips hinge not squat to the bar','Bar stays in contact with shins','Squeeze glutes at lockout','Do not hyperextend lower back at top'],'The king of posterior chain development. Builds total-body strength that transfers to every sport.','intermediate',ARRAY['barbell'],ARRAY['glutes','hamstrings','lower_back'],ARRAY['quadriceps','upper_back','core']),
('romanian_deadlift','Romanian Deadlift','hinge','conventional','{posterior_chain,hyrox,crossfit,athx,bilateral,barbell,dumbbell}','https://www.youtube.com/watch?v=JCXUYuzwNrM','JCXUYuzwNrM',ARRAY['Soft bend in knees throughout','Push hips back not down','Bar stays close to legs','Feel stretch in hamstrings at bottom'],'The primary hamstring and glute builder. Safer spine position for high-rep accessory work.','beginner',ARRAY['barbell','dumbbell'],ARRAY['hamstrings','glutes'],ARRAY['lower_back','core']),
('single_leg_rdl','Single-Leg RDL','hinge','single_leg','{hyrox,running_economy,unilateral,single_leg,dumbbell,kettlebell}','https://www.youtube.com/watch?v=gnt5DTn7wT8','gnt5DTn7wT8',ARRAY['Hip hinge on standing leg','Hips stay square do not rotate','Soft bend in standing knee','Reach weight straight down'],'Critical for Hyrox athletes. Builds hip stability and single-leg hamstring strength.','intermediate',ARRAY['dumbbell','kettlebell'],ARRAY['hamstrings','glutes'],ARRAY['core','hip_stabilizers']),
('good_morning','Good Morning','hinge','good_morning','{posterior_chain,athx,crossfit,bilateral,barbell}','https://www.youtube.com/watch?v=YA-h3n9L4YU','YA-h3n9L4YU',ARRAY['Bar on upper traps','Soft knee bend','Hinge at hip not lower back','Keep neutral spine throughout'],'Develops erector and hamstring strength in a stretched position.','intermediate',ARRAY['barbell'],ARRAY['hamstrings','lower_back'],ARRAY['glutes','core']),
('trap_bar_deadlift','Trap Bar Deadlift','hinge','conventional','{athx,explosive,bilateral,trap_bar,strength}','https://www.youtube.com/watch?v=kSKrKBzfWEQ','kSKrKBzfWEQ',ARRAY['Stand in center of bar','Sit back and down to handles','Drive floor away','Lockout hips and knees simultaneously'],'More quad involvement than conventional DL. Excellent for ATHX athletes building total-body power.','beginner',ARRAY['trap_bar'],ARRAY['glutes','quadriceps','hamstrings'],ARRAY['lower_back','upper_back','core']),
('glute_ham_raise','Glute-Ham Raise','hinge','single_leg','{posterior_chain,athx,crossfit,ghr_machine}','https://www.youtube.com/watch?v=L_2Pn_R3HmQ','L_2Pn_R3HmQ',ARRAY['Toes locked in knees at pad edge','Lower slowly under control','Drive through toes to rise','Squeeze hamstrings at top'],'One of the most demanding hamstring exercises. Builds posterior chain for sprinting and jumping.','advanced',ARRAY['ghr_machine'],ARRAY['hamstrings','glutes'],ARRAY['lower_back','calves']),
('hip_thrust','Hip Thrust','hinge','hip_extension','{hyrox,crossfit,athx,barbell,dumbbell,glutes}','https://www.youtube.com/watch?v=xDmFkJxPzeM','xDmFkJxPzeM',ARRAY['Shoulders on bench bar at hip crease','Drive through heels','Full hip extension at top','Squeeze glutes hard at lockout'],'The most effective isolated glute exercise. Critical for Hyrox sled pushing and running power.','beginner',ARRAY['barbell','bench'],ARRAY['glutes'],ARRAY['hamstrings','core','hip_stabilizers']),
('strict_press','Strict Press','press_vertical','strict','{crossfit,athx,overhead,barbell,shoulder_strength}','https://www.youtube.com/watch?v=2yjwXTZQDDI','2yjwXTZQDDI',ARRAY['Bar starts at collarbone','Squeeze glutes and brace core','Press to full lockout ears through arms','No leg drive at all'],'The foundation of overhead strength. No other movement builds strict shoulder pressing as efficiently.','beginner',ARRAY['barbell','rack'],ARRAY['deltoids','triceps'],ARRAY['core','upper_back','traps']),
('push_press','Push Press','press_vertical','push','{crossfit,athx,overhead,barbell,power}','https://www.youtube.com/watch?v=X6-DMh-t4nQ','X6-DMh-t4nQ',ARRAY['Dip is shallow and fast','Drive legs then arms','Press the bar do not push yourself under','Lockout overhead not in front'],'Allows heavier overhead loading than strict press. Builds barbell cycling capacity.','intermediate',ARRAY['barbell'],ARRAY['deltoids','triceps','quadriceps'],ARRAY['core','traps']),
('z_press','Z-Press','press_vertical','strict','{crossfit,overhead,barbell,dumbbell,shoulder_strength,mobility}','https://www.youtube.com/watch?v=rjkA7AbRLZk','rjkA7AbRLZk',ARRAY['Seated on floor legs straight out','Cannot use hips or legs at all','Forces vertical torso','Heavy core demand throughout'],'Seated floor press that eliminates all leg drive. Exposes and fixes shoulder and thoracic weaknesses.','intermediate',ARRAY['barbell','dumbbell'],ARRAY['deltoids','triceps'],ARRAY['core','upper_back','serratus']),
('landmine_press','Landmine Press','press_vertical','landmine','{crossfit,athx,overhead,landmine,shoulder_prehab}','https://www.youtube.com/watch?v=utEdUG_Wg4o','utEdUG_Wg4o',ARRAY['Press at 45-degree angle','Single arm staggered stance','Full extension at top','Control the return'],'Shoulder-friendly overhead pressing variation. Excellent for athletes with overhead mobility restrictions.','beginner',ARRAY['barbell','landmine_attachment'],ARRAY['deltoids','triceps','upper_pec'],ARRAY['core','serratus']),
('bench_press','Bench Press','press_horizontal','bench','{athx,strength,barbell,bilateral,upper_body}','https://www.youtube.com/watch?v=rT7DgCr-3pg','rT7DgCr-3pg',ARRAY['Feet flat on floor','Slight arch in lower back','Bar touches low chest','Drive feet through floor on press'],'Primary horizontal push strength movement. Builds upper body pressing foundation.','beginner',ARRAY['barbell','bench'],ARRAY['pectorals','triceps'],ARRAY['deltoids','core']),
('floor_press','Floor Press','press_horizontal','floor','{athx,crossfit,dumbbell,barbell,upper_body}','https://www.youtube.com/watch?v=uUGDRwge4F8','uUGDRwge4F8',ARRAY['Elbows rest on floor between reps','No leg drive from floor position','Pause at bottom','Full lockout at top'],'Horizontal press from the floor. Eliminates leg drive. Builds tricep lockout strength.','beginner',ARRAY['barbell','dumbbell'],ARRAY['pectorals','triceps'],ARRAY['deltoids']),
('db_bench_press','Dumbbell Bench Press','press_horizontal','dumbbell','{athx,crossfit,dumbbell,bilateral,upper_body}','https://www.youtube.com/watch?v=QsYre__-aro','QsYre__-aro',ARRAY['Greater range of motion than barbell','Keep wrists stacked over elbows','Control the stretch at bottom','Press and rotate slightly at top'],'Greater range of motion than barbell bench. Addresses left-right imbalances.','beginner',ARRAY['dumbbell','bench'],ARRAY['pectorals','triceps'],ARRAY['deltoids','core']),
('weighted_pullup','Weighted Pull-Up','pull_vertical','pullup','{crossfit,athx,barbell,bodyweight,pulling_strength}','https://www.youtube.com/watch?v=eGo4IYlbE5g','eGo4IYlbE5g',ARRAY['Dead hang start','Pull elbows to hips not back','Chin clears bar','Full extension at bottom between reps'],'The primary vertical pulling strength movement. Directly builds muscle-up and bar muscle-up strength.','intermediate',ARRAY['pull_up_bar','weight_belt'],ARRAY['latissimus_dorsi','biceps'],ARRAY['rhomboids','core','rear_delts']),
('lat_pulldown','Lat Pulldown','pull_vertical','lat_pulldown','{crossfit,athx,cable_machine,pulling_strength}','https://www.youtube.com/watch?v=CAwf7n6Luuc','CAwf7n6Luuc',ARRAY['Lean back slightly','Pull elbows to hips','Squeeze lats at bottom','Control the return fully'],'Machine-based vertical pulling. Useful when building pull-up strength or managing fatigue.','beginner',ARRAY['cable_machine'],ARRAY['latissimus_dorsi','biceps'],ARRAY['rhomboids','rear_delts']),
('pullover','Dumbbell Pullover','pull_vertical','pullover','{hyrox,crossfit,dumbbell,lat_strength,skierg}','https://www.youtube.com/watch?v=FK4rHCCTNnY','FK4rHCCTNnY',ARRAY['Lie across bench','Slight bend in elbows throughout','Full stretch overhead','Pull through lats not arms'],'Directly targets the lat engagement pattern used on the SkiErg. Excellent Hyrox-specific accessory.','beginner',ARRAY['dumbbell','bench'],ARRAY['latissimus_dorsi','serratus'],ARRAY['triceps','chest']),
('pendlay_row','Pendlay Row','pull_horizontal','row','{athx,crossfit,barbell,pulling_strength,posterior_chain}','https://www.youtube.com/watch?v=oPasENyOo0c','oPasENyOo0c',ARRAY['Horizontal torso not 45 degrees','Bar rests on floor between reps','Explosive concentric pull','Row to lower chest'],'Strict horizontal pull from a dead stop each rep. Builds upper back strength and power.','intermediate',ARRAY['barbell'],ARRAY['rhomboids','latissimus_dorsi','rear_delts'],ARRAY['biceps','core']),
('single_arm_db_row','Single-Arm Dumbbell Row','pull_horizontal','row','{crossfit,athx,dumbbell,unilateral,pulling_strength}','https://www.youtube.com/watch?v=dFzUjzfih7k','dFzUjzfih7k',ARRAY['Support on bench with same-side hand','Elbow drives back and up','Full stretch at bottom','No hip rotation'],'The go-to unilateral pulling accessory. Addresses imbalances and supports overhead gymnastics.','beginner',ARRAY['dumbbell','bench'],ARRAY['latissimus_dorsi','rhomboids'],ARRAY['biceps','rear_delts','core']),
('face_pull','Face Pull','pull_horizontal','face_pull','{crossfit,athx,cable_machine,shoulder_prehab,rear_delt}','https://www.youtube.com/watch?v=rep-qVOkqgk','rep-qVOkqgk',ARRAY['Pull to face not neck','External rotate at end of pull','Elbows at or above shoulder height','Light weight high control'],'Critical shoulder health movement. Balances pressing volume in CrossFit and ATHX programming.','beginner',ARRAY['cable_machine','resistance_band'],ARRAY['rear_deltoids','external_rotators'],ARRAY['rhomboids','traps']),
('banded_pull_apart','Banded Pull-Apart','pull_horizontal','face_pull','{crossfit,hyrox,resistance_band,shoulder_prehab,warmup}','https://www.youtube.com/watch?v=M-dKuEBFpd0','M-dKuEBFpd0',ARRAY['Arms straight throughout','Pull to chest level','Squeeze shoulder blades together','Slow and controlled'],'Shoulder health staple. Used as warm-up or between pressing sets to activate rear delts.','beginner',ARRAY['resistance_band'],ARRAY['rear_deltoids','rhomboids'],ARRAY['traps','external_rotators']),
('farmer_carry','Farmer Carry','carry','farmer','{hyrox,athx,dumbbell,kettlebell,trap_bar,loaded_carry,grip}','https://www.youtube.com/watch?v=rt0UCPuT7ws','rt0UCPuT7ws',ARRAY['Stand tall do not lean','Short powerful steps','Brace core the entire duration','Keep shoulders packed down'],'The most race-specific carry for Hyrox. Builds grip core stability and loaded locomotion strength.','beginner',ARRAY['dumbbell','kettlebell','trap_bar'],ARRAY['core','traps','grip'],ARRAY['quadriceps','glutes','shoulder_stabilizers']),
('suitcase_carry','Suitcase Carry','carry','suitcase','{hyrox,athx,dumbbell,kettlebell,unilateral,core,anti_lateral_flexion}','https://www.youtube.com/watch?v=RxKR6LdjI6E','RxKR6LdjI6E',ARRAY['Single weight on one side only','Resist leaning toward weight','Hips stay level','Core braces against lateral bend'],'Unilateral carry that challenges anti-lateral flexion core strength. Builds stability for the Hyrox sandbag carry.','beginner',ARRAY['dumbbell','kettlebell'],ARRAY['core','obliques','grip'],ARRAY['quadriceps','glutes','hip_stabilizers']),
('power_clean','Power Clean','olympic','clean','{crossfit,athx,olympic,barbell,explosive,power}','https://www.youtube.com/watch?v=GdoCafqYo3Q','GdoCafqYo3Q',ARRAY['Bar stays close to body','Jump and shrug aggressively','Catch in quarter-squat','Elbows snap through fast'],'Full-body explosive movement. Builds the power and coordination that transfers to CrossFit and ATHX.','intermediate',ARRAY['barbell'],ARRAY['glutes','hamstrings','traps'],ARRAY['quadriceps','core','deltoids']),
('hang_power_clean','Hang Power Clean','olympic','clean','{crossfit,athx,olympic,barbell,explosive,power}','https://www.youtube.com/watch?v=P9SkIPzaRJ0','P9SkIPzaRJ0',ARRAY['Start at mid-thigh','Push hips back then drive forward','Aggressive elbow turnover','Catch in athletic position'],'Hang position forces focus on hip extension and turnover without the pull from the floor.','intermediate',ARRAY['barbell'],ARRAY['glutes','hamstrings','traps'],ARRAY['quadriceps','core']),
('hang_power_snatch','Hang Power Snatch','olympic','snatch','{crossfit,athx,olympic,barbell,explosive,overhead}','https://www.youtube.com/watch?v=cLGOBe0OEXY','cLGOBe0OEXY',ARRAY['Wide snatch grip','Hips back bar at thigh','Violent hip extension and shrug','Punch overhead and lock out'],'Builds overhead power and bar path efficiency. Trains the receiving position overhead under speed.','advanced',ARRAY['barbell'],ARRAY['glutes','hamstrings','deltoids'],ARRAY['traps','core','triceps']),
('box_jump','Box Jump','explosive','box_jump','{crossfit,athx,hyrox,bodyweight,explosive,power,plyo}','https://www.youtube.com/watch?v=52r_Ul5k03g','52r_Ul5k03g',ARRAY['Load hips before jumping','Land softly in partial squat','Full hip extension at top','Step down do not jump down'],'Primary lower body power and rate-of-force development tool. Used across all three sports.','beginner',ARRAY['plyo_box'],ARRAY['glutes','quadriceps','calves'],ARRAY['hamstrings','core']),
('jump_squat','Jump Squat','explosive','jump_squat','{athx,crossfit,barbell,dumbbell,bodyweight,explosive,power}','https://www.youtube.com/watch?v=CnBmiBqp-AI','CnBmiBqp-AI',ARRAY['Quarter squat depth','Explode through full extension','Land soft absorb through hips','Immediate rebound for touch-and-go sets'],'Loaded explosive power development. ATHX-specific tool for building rate of force development under load.','intermediate',ARRAY['barbell','dumbbell','bodyweight'],ARRAY['quadriceps','glutes'],ARRAY['calves','core']),
('pallof_press','Pallof Press','core','anti_rotation','{crossfit,hyrox,athx,cable_machine,resistance_band,core,anti_rotation}','https://www.youtube.com/watch?v=AH_QZLm_0-s','AH_QZLm_0-s',ARRAY['Anchor at chest height','Press out resist rotation','Hips square throughout','Exhale on press'],'The gold standard anti-rotation core exercise. Builds lateral core stability for carries and running.','beginner',ARRAY['cable_machine','resistance_band'],ARRAY['obliques','transverse_abdominis'],ARRAY['glutes','hip_stabilizers']),
('calf_raise','Calf Raise','accessory','isolation','{hyrox,running_economy,bodyweight,dumbbell,ankle_stability}','https://www.youtube.com/watch?v=gwLzBJYoWlI','gwLzBJYoWlI',ARRAY['Full range of motion','Pause at top','Slow controlled descent','Single-leg for progression'],'Neglected but essential for running athletes. Builds ankle stiffness and calf endurance.','beginner',ARRAY['bodyweight','dumbbell','machine'],ARRAY['gastrocnemius','soleus'],ARRAY['tibialis_anterior']),
('nordic_hamstring_curl','Nordic Hamstring Curl','hinge','nordic','{crossfit,hyrox,athx,posterior_chain,bodyweight,injury_prevention}','https://www.youtube.com/watch?v=d8PSL8GKgX4','d8PSL8GKgX4',ARRAY['Knees anchored firmly','Descend as slowly as possible','Use hands to catch at bottom','Drive back up through hamstrings not arms'],'One of the most effective hamstring injury-prevention exercises. Builds eccentric hamstring strength at long muscle lengths.','advanced',ARRAY['bodyweight','ghr_machine'],ARRAY['hamstrings'],ARRAY['glutes','calves']),
('tricep_pushdown','Tricep Pushdown','press_horizontal','isolation','{crossfit,athx,cable_machine,tricep,elbow_lockout}','https://www.youtube.com/watch?v=2-LAMcpzODU','2-LAMcpzODU',ARRAY['Elbows stay at sides throughout','Full extension at bottom','Control the return slowly','Do not lean forward excessively'],'Isolates the triceps for lockout strength. Supports overhead pressing and barbell cycling capacity.','beginner',ARRAY['cable_machine','resistance_band'],ARRAY['triceps'],ARRAY['forearms']),
('copenhagen_plank','Copenhagen Plank','core','lateral','{hyrox,crossfit,athx,bodyweight,adductor,hip_stability}','https://www.youtube.com/watch?v=9KAibGNt4q4','9KAibGNt4q4',ARRAY['Top leg on bench lower leg free','Maintain neutral pelvis','Drive hip up do not sag','Progress from knees to full leg'],'Builds adductor and lateral hip strength that is frequently undertrained. Directly supports running economy and single-leg stability.','intermediate',ARRAY['bench','bodyweight'],ARRAY['adductors','obliques'],ARRAY['hip_abductors','core']);

-- ============================================================
-- WORKOUT TEMPLATES (14+ rows)
-- ============================================================
insert into workouts (id, sport, subtrack, week_number, day_number, title, coach_note, warmup, main_work, accessory) values

('hyrox_sled_w1d1','hyrox','sled_carry_strength',1,1,'Sled Foundation — Lower Body Drive',
'Week 1 is about establishing baseline strength in the hip drive patterns that power your sled. Keep all RPEs honest — this is not a max effort week. If anything feels heavier than prescribed, reduce the load.',
'["3 min easy bike or row","2x10 glute bridges","2x10 goblet squat with 3-second pause at bottom","2x10 banded pull-apart","Hip 90/90 stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"safety_bar_squat","name":"Safety Bar Squat","sets":4,"reps":"6","rpe_target":7,"rest_seconds":180,"description":"Focus on depth and control. Keep chest up and drive knees out."},{"movement_id":"romanian_deadlift","name":"Romanian Deadlift","sets":4,"reps":"8","rpe_target":7,"rest_seconds":150,"description":"Push hips back until you feel a deep hamstring stretch. Bar stays close to legs throughout."},{"movement_id":"bulgarian_split_squat","name":"Bulgarian Split Squat","sets":3,"reps":"8 each leg","rpe_target":7,"rest_seconds":120,"description":"Rear foot on bench. Front shin vertical. Drive through front heel. Full range of motion."}]'::jsonb,
'[{"movement_id":"hip_thrust","name":"Hip Thrust","sets":3,"reps":"12","rpe_target":6,"rest_seconds":90,"description":"Full hip extension and a hard glute squeeze at the top. Controlled descent."},{"movement_id":"farmer_carry","name":"Farmer Carry","sets":4,"reps":"30 meters","rpe_target":7,"rest_seconds":90,"description":"Stand tall. Short powerful steps. Brace core the entire distance. Use a challenging but manageable load."}]'::jsonb),

('hyrox_sled_w1d2','hyrox','sled_carry_strength',1,2,'Unilateral Power — Single Leg Focus',
'Day 2 shifts to single-leg work which is where most Hyrox athletes are most underdeveloped. Do not rush the single-leg RDL — quality of movement matters more than load here.',
'["3 min easy jog or row","2x8 single-leg glute bridge each side","2x10 step-up bodyweight","Hip flexor stretch 60 seconds each side","Ankle circles 20 each direction"]'::jsonb,
'[{"movement_id":"single_leg_rdl","name":"Single-Leg RDL","sets":4,"reps":"8 each leg","rpe_target":7,"rest_seconds":120,"description":"Hip hinge on standing leg. Free weight hangs straight down. Hips stay square — do not rotate toward the raised leg."},{"movement_id":"step_up","name":"Step-Up","sets":4,"reps":"10 each leg","rpe_target":7,"rest_seconds":120,"description":"Use a box at knee height. Drive through the working heel only — do not push off the back foot at all."},{"movement_id":"bulgarian_split_squat","name":"Bulgarian Split Squat","sets":3,"reps":"10 each leg","rpe_target":6.5,"rest_seconds":120,"description":"Slightly lighter than Day 1. Focus on smooth controlled movement rather than load."}]'::jsonb,
'[{"movement_id":"suitcase_carry","name":"Suitcase Carry","sets":4,"reps":"25 meters each side","rpe_target":7,"rest_seconds":90,"description":"Heavy enough that you feel the pull to lean. Resist it completely. Hips level the entire distance."},{"movement_id":"calf_raise","name":"Calf Raise","sets":3,"reps":"20","rpe_target":6,"rest_seconds":60,"description":"Full range of motion. Pause at top for 1 second. Slow controlled descent over 3 seconds."}]'::jsonb),

('hyrox_sled_w2d1','hyrox','sled_carry_strength',2,1,'Week 2 — Loading Up',
'Add 5-10% load to all main work this week. The patterns from Week 1 should feel familiar now — this week we test whether you can maintain them under more load.',
'["3 min easy bike or row","2x10 glute bridges","2x8 goblet squat","2x10 banded pull-apart","Hip 90/90 stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"safety_bar_squat","name":"Safety Bar Squat","sets":4,"reps":"5","rpe_target":7.5,"rest_seconds":180,"description":"Add 5-10 lbs from last week. Same depth and control — do not sacrifice position for load."},{"movement_id":"romanian_deadlift","name":"Romanian Deadlift","sets":4,"reps":"6","rpe_target":7.5,"rest_seconds":150,"description":"Slightly heavier than Week 1. Still focused on hamstring stretch and bar path."},{"movement_id":"conventional_deadlift","name":"Conventional Deadlift","sets":3,"reps":"5","rpe_target":7.5,"rest_seconds":180,"description":"Replaces split squat this session. Hinge pattern focus. Bar close to shins, lockout fully at top."}]'::jsonb,
'[{"movement_id":"hip_thrust","name":"Hip Thrust","sets":3,"reps":"10","rpe_target":7,"rest_seconds":90,"description":"Add a small amount of load from last week. Hard squeeze and hold 1 second at the top."},{"movement_id":"farmer_carry","name":"Farmer Carry","sets":4,"reps":"40 meters","rpe_target":7.5,"rest_seconds":90,"description":"Increase distance or load from Week 1. Maintain perfect posture for the full distance."}]'::jsonb),

('hyrox_sled_w2d2','hyrox','sled_carry_strength',2,2,'Week 2 — Unilateral Volume',
'Slightly more volume on single-leg work this week. The suitcase carry load should be genuinely challenging — if you can walk without any lateral lean it is probably too light.',
'["3 min easy jog or row","2x8 single-leg glute bridge each side","2x10 step-up bodyweight","Hip flexor stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"single_leg_rdl","name":"Single-Leg RDL","sets":4,"reps":"10 each leg","rpe_target":7.5,"rest_seconds":120,"description":"Add a small amount of load from Week 1. Movement quality first — add load only if you stayed perfectly square last week."},{"movement_id":"step_up","name":"Step-Up","sets":4,"reps":"12 each leg","rpe_target":7,"rest_seconds":120,"description":"Add small load — hold dumbbells at sides. Drive through front heel exclusively."},{"movement_id":"bulgarian_split_squat","name":"Bulgarian Split Squat","sets":4,"reps":"8 each leg","rpe_target":7.5,"rest_seconds":120,"description":"Add a set from last week. Maintain full range and 2-second descent."}]'::jsonb,
'[{"movement_id":"suitcase_carry","name":"Suitcase Carry","sets":4,"reps":"30 meters each side","rpe_target":7.5,"rest_seconds":90,"description":"Increase distance or load from Week 1. The challenge is resisting lateral flexion — heavier is only better if posture holds."},{"movement_id":"pallof_press","name":"Pallof Press","sets":3,"reps":"10 each side","rpe_target":6,"rest_seconds":60,"description":"New movement this week. Press out and hold 2 seconds. Hips absolutely square throughout."}]'::jsonb),

('cf_overhead_w1d1','crossfit','overhead_shoulder_strength',1,1,'Overhead Foundation — Strict Pressing',
'Week 1 Day 1 establishes your strict pressing baseline. The Z-Press will feel humbling — that is the point. No leg drive, no momentum. Whatever you can lift here with perfect form is your true overhead strength.',
'["3 min easy row or bike","2x10 banded pull-apart","2x10 band pull-apart overhead","2x8 strict press empty bar","Shoulder 90-90 stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"strict_press","name":"Strict Press","sets":5,"reps":"5","rpe_target":7,"rest_seconds":180,"description":"Bar starts at collarbone. Squeeze glutes and brace core hard before every rep. Full lockout with ears through arms at top."},{"movement_id":"z_press","name":"Z-Press","sets":4,"reps":"8","rpe_target":6.5,"rest_seconds":150,"description":"Seated on floor, legs straight. No hip drive possible. This exposes exactly what your overhead strength really is. Start light."},{"movement_id":"push_press","name":"Push Press","sets":3,"reps":"5","rpe_target":7,"rest_seconds":150,"description":"Dip is shallow and fast. Drive legs then immediately press. Lockout overhead — do not press it forward."}]'::jsonb,
'[{"movement_id":"face_pull","name":"Face Pull","sets":4,"reps":"15","rpe_target":6,"rest_seconds":60,"description":"Pull to face level. External rotate at the end position. Light weight with high control — this is shoulder health work, not a strength exercise."},{"movement_id":"banded_pull_apart","name":"Banded Pull-Apart","sets":3,"reps":"20","rpe_target":5,"rest_seconds":45,"description":"Arms straight. Pull to chest level. Slow and controlled. Feel the rear delts and rhomboids working."}]'::jsonb),

('cf_overhead_w1d2','crossfit','overhead_shoulder_strength',1,2,'Overhead — Vertical Pulling Balance',
'Every overhead pressing track must balance with vertical pulling. Today''s session is pulling-dominant intentionally. CrossFit athletes press far more than they pull and this imbalance limits overhead stability and increases injury risk.',
'["3 min easy row","2x10 scap pull-up","2x10 banded pull-apart","Dead hang 30 seconds","Lat stretch in doorframe 60 seconds each side"]'::jsonb,
'[{"movement_id":"weighted_pullup","name":"Weighted Pull-Up","sets":5,"reps":"4","rpe_target":7.5,"rest_seconds":180,"description":"Dead hang start. Pull elbows to hips — do not think about the bar, think about your elbows driving down. Full extension at bottom of every rep."},{"movement_id":"landmine_press","name":"Landmine Press","sets":4,"reps":"8 each arm","rpe_target":6.5,"rest_seconds":120,"description":"Single arm, staggered stance. Press at a 45-degree angle. Good option if strict pressing causes any shoulder discomfort."},{"movement_id":"strict_press","name":"Strict Press","sets":3,"reps":"8","rpe_target":6.5,"rest_seconds":150,"description":"Lighter than Day 1. Volume day — not max effort. Focus on bar path and lockout quality."}]'::jsonb,
'[{"movement_id":"single_arm_db_row","name":"Single-Arm Dumbbell Row","sets":4,"reps":"12 each arm","rpe_target":6.5,"rest_seconds":90,"description":"Support on bench. Elbow drives back and up. Full stretch at the bottom. No hip rotation."},{"movement_id":"face_pull","name":"Face Pull","sets":3,"reps":"15","rpe_target":5.5,"rest_seconds":60,"description":"Same as Day 1. Keep it light. External rotation at the end range is the point."}]'::jsonb),

('cf_overhead_w2d1','crossfit','overhead_shoulder_strength',2,1,'Week 2 — Pressing Load Increase',
'Add load to the strict press and push press this week. The Z-Press load can stay the same — we are adding a rep instead. If the strict press bar path started drifting forward in Week 1 that is the cue to fix before adding weight.',
'["3 min easy row or bike","2x10 banded pull-apart","2x8 strict press empty bar","Shoulder circles 10 each direction"]'::jsonb,
'[{"movement_id":"strict_press","name":"Strict Press","sets":5,"reps":"4","rpe_target":7.5,"rest_seconds":180,"description":"Add 5 lbs from Week 1. Four reps at slightly higher intensity. Perfect bar path — bar should travel straight up, not forward."},{"movement_id":"z_press","name":"Z-Press","sets":4,"reps":"10","rpe_target":7,"rest_seconds":150,"description":"Same load as Week 1, two more reps. The extra volume will be felt. Do not let the torso collapse at rep 8-10."},{"movement_id":"push_press","name":"Push Press","sets":4,"reps":"4","rpe_target":7.5,"rest_seconds":150,"description":"Add a set and a small amount of load. Dip stays shallow and fast — a slow dip kills the transfer of force."}]'::jsonb,
'[{"movement_id":"face_pull","name":"Face Pull","sets":4,"reps":"15","rpe_target":6,"rest_seconds":60,"description":"Same protocol as Week 1. This is a permanent fixture in the programming — it protects the shoulder."},{"movement_id":"banded_pull_apart","name":"Banded Pull-Apart","sets":3,"reps":"20","rpe_target":5,"rest_seconds":45,"description":"Can step up to a slightly more resistant band this week if last week felt very easy."}]'::jsonb),

('cf_overhead_w2d2','crossfit','overhead_shoulder_strength',2,2,'Week 2 — Pulling Strength Up',
'Weighted pull-up load goes up this week. If you hit all reps in Week 1 with the last set at RPE 7.5 or below add more weight. If it was RPE 8+ stay at the same load and aim for one extra rep on the last set.',
'["3 min easy row","2x10 scap pull-up","2x10 banded pull-apart","Dead hang 30 seconds"]'::jsonb,
'[{"movement_id":"weighted_pullup","name":"Weighted Pull-Up","sets":5,"reps":"4","rpe_target":8,"rest_seconds":180,"description":"Increase load from Week 1 if all reps were clean. Dead hang start non-negotiable. Four reps with weight beats six reps with momentum."},{"movement_id":"landmine_press","name":"Landmine Press","sets":4,"reps":"10 each arm","rpe_target":7,"rest_seconds":120,"description":"Add two reps from Week 1. Maintain the 45-degree pressing angle throughout — do not let it drift to horizontal."},{"movement_id":"push_press","name":"Push Press","sets":3,"reps":"6","rpe_target":7,"rest_seconds":150,"description":"Lighter load, more reps. Barbell cycling focus this session — smooth and efficient between reps."}]'::jsonb,
'[{"movement_id":"single_arm_db_row","name":"Single-Arm Dumbbell Row","sets":4,"reps":"14 each arm","rpe_target":7,"rest_seconds":90,"description":"Add two reps from Week 1. Add a small amount of load if 12 reps felt like RPE 6 or below."},{"movement_id":"face_pull","name":"Face Pull","sets":3,"reps":"15","rpe_target":5.5,"rest_seconds":60,"description":"Unchanged from Week 1. Consistency here matters more than progression."}]'::jsonb),

('cf_lower_w1d1','crossfit','lower_body_strength',1,1,'Lower Body Foundation — Bilateral Squat',
'The back squat is the cornerstone of this track. Week 1 is deliberately moderate — we need to see how your body responds to the squat volume on top of your regular CrossFit training before we push the intensity.',
'["3 min bike or row","2x10 goblet squat with 3-second pause","2x10 glute bridge","Hip 90/90 stretch 60 seconds each side","Ankle dorsiflexion stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"back_squat","name":"Back Squat","sets":5,"reps":"5","rpe_target":7,"rest_seconds":180,"description":"Full depth — crease of hip below top of knee. Controlled descent 2 seconds. Drive knees out on the way up. Bar on upper traps."},{"movement_id":"romanian_deadlift","name":"Romanian Deadlift","sets":4,"reps":"8","rpe_target":6.5,"rest_seconds":150,"description":"Posterior chain balance to the squat. Push hips back until deep hamstring stretch. Bar close to legs throughout."},{"movement_id":"pause_squat","name":"Pause Squat","sets":3,"reps":"4","rpe_target":6.5,"rest_seconds":180,"description":"3-second pause at the bottom. Significantly lighter than the working back squat. Builds bottom position strength and awareness."}]'::jsonb,
'[{"movement_id":"goblet_squat","name":"Goblet Squat","sets":3,"reps":"12","rpe_target":6,"rest_seconds":90,"description":"Light and controlled. Perfect mechanics. This is movement quality work at the end of the session."},{"movement_id":"glute_ham_raise","name":"Glute-Ham Raise","sets":3,"reps":"8","rpe_target":7,"rest_seconds":90,"description":"Control the descent over 3 seconds. Drive through toes on the way up. If GHR machine is unavailable sub with Nordic hamstring curl using a partner."}]'::jsonb),

('cf_lower_w1d2','crossfit','lower_body_strength',1,2,'Lower Body — Unilateral and Hinge',
'Day 2 shifts to single-leg and hinge-dominant work. Most CrossFit athletes have a meaningful strength difference between their left and right legs — the Bulgarian split squat will expose this quickly. Do not add load to compensate for asymmetry.',
'["3 min easy row","2x8 single-leg glute bridge each side","2x10 hip hinge with dowel","Hip flexor stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"bulgarian_split_squat","name":"Bulgarian Split Squat","sets":4,"reps":"8 each leg","rpe_target":7,"rest_seconds":120,"description":"Rear foot on bench. Front shin stays vertical. Full range. If one side is noticeably weaker start with that side and match the reps on the stronger side."},{"movement_id":"conventional_deadlift","name":"Conventional Deadlift","sets":4,"reps":"5","rpe_target":7.5,"rest_seconds":180,"description":"Hinge dominant day. Bar close to shins. Full lockout at top — hips and knees lock simultaneously."},{"movement_id":"single_leg_rdl","name":"Single-Leg RDL","sets":3,"reps":"10 each leg","rpe_target":6.5,"rest_seconds":120,"description":"Build the single-leg hinge. Start with a light dumbbell. Focus entirely on hip hinging with a square pelvis."}]'::jsonb,
'[{"movement_id":"hip_thrust","name":"Hip Thrust","sets":3,"reps":"12","rpe_target":6.5,"rest_seconds":90,"description":"Direct glute isolation at the end of a demanding session. Hard squeeze and 1-second hold at the top of each rep."},{"movement_id":"good_morning","name":"Good Morning","sets":3,"reps":"10","rpe_target":6,"rest_seconds":90,"description":"Light load. This is a hamstring and erector stretch-and-strengthen. Do not load this movement heavily."}]'::jsonb),

('cf_lower_w2d1','crossfit','lower_body_strength',2,1,'Week 2 — Squat Intensity Up',
'Add load to the back squat this week. The pause squat weight can stay similar — we are adding load to the main squat and letting the pause work reinforce the bottom position at a manageable intensity.',
'["3 min bike or row","2x10 goblet squat","2x10 glute bridge","Hip 90/90 60 seconds each side"]'::jsonb,
'[{"movement_id":"back_squat","name":"Back Squat","sets":5,"reps":"4","rpe_target":7.5,"rest_seconds":180,"description":"Add 5-10 lbs from Week 1. Four reps allows slightly more load than five. Same depth and control standards apply."},{"movement_id":"romanian_deadlift","name":"Romanian Deadlift","sets":4,"reps":"6","rpe_target":7.5,"rest_seconds":150,"description":"Add small load from Week 1. Six reps at higher intensity than the eight-rep sets last week."},{"movement_id":"pause_squat","name":"Pause Squat","sets":3,"reps":"4","rpe_target":7,"rest_seconds":180,"description":"Can add a very small amount of load from Week 1 if bottom position felt solid. Still well below your working back squat load."}]'::jsonb,
'[{"movement_id":"goblet_squat","name":"Goblet Squat","sets":3,"reps":"12","rpe_target":6.5,"rest_seconds":90,"description":"Slightly heavier than Week 1. Same movement quality focus."},{"movement_id":"glute_ham_raise","name":"Glute-Ham Raise","sets":3,"reps":"10","rpe_target":7,"rest_seconds":90,"description":"Add two reps from Week 1. Same controlled descent tempo."}]'::jsonb),

('cf_lower_w2d2','crossfit','lower_body_strength',2,2,'Week 2 — Unilateral Load Progression',
'The split squat load goes up this week. More importantly the deadlift gets its first real intensity day. Keep the single-leg RDL at the same load — add reps instead.',
'["3 min easy row","2x8 single-leg glute bridge each side","2x10 hip hinge with dowel","Hip flexor stretch 60 seconds each side"]'::jsonb,
'[{"movement_id":"bulgarian_split_squat","name":"Bulgarian Split Squat","sets":4,"reps":"8 each leg","rpe_target":7.5,"rest_seconds":120,"description":"Add load from Week 1. Maintain full range and 2-second descent. Do not sacrifice range of motion for load."},{"movement_id":"conventional_deadlift","name":"Conventional Deadlift","sets":4,"reps":"4","rpe_target":8,"rest_seconds":180,"description":"First true intensity day on the deadlift. Four reps at RPE 8 means the fourth rep is hard but form does not break. Reset completely between reps."},{"movement_id":"single_leg_rdl","name":"Single-Leg RDL","sets":3,"reps":"12 each leg","rpe_target":7,"rest_seconds":120,"description":"Same load as Week 1, two more reps. If Week 1 felt easy add a small amount of load here."}]'::jsonb,
'[{"movement_id":"hip_thrust","name":"Hip Thrust","sets":4,"reps":"10","rpe_target":7,"rest_seconds":90,"description":"Add a set from Week 1. Squeeze and hold 1 second at top of each rep."},{"movement_id":"good_morning","name":"Good Morning","sets":3,"reps":"12","rpe_target":6,"rest_seconds":90,"description":"Add two reps from Week 1. Same light load. Hamstring stretch and erector work."}]'::jsonb),

('athx_explosive_w1d1','athx','explosive_power',1,1,'Explosive Foundation — Power Development',
'ATHX demands explosive output across multiple modalities. Week 1 Day 1 establishes the power clean and box jump as your primary explosive tools. Quality of movement at moderate loads beats heavy ugly reps every time on these exercises.',
'["3 min easy bike","2x5 box jump bodyweight focusing on landing","2x3 hang power clean empty bar","Hip 90/90 stretch 60 seconds each side","Ankle circles 20 each direction"]'::jsonb,
'[{"movement_id":"power_clean","name":"Power Clean","sets":5,"reps":"3","rpe_target":7,"rest_seconds":180,"description":"Bar close to body throughout. Jump and shrug aggressively. Catch in a solid quarter-squat. Reset and rebrace fully between every rep."},{"movement_id":"trap_bar_deadlift","name":"Trap Bar Deadlift","sets":4,"reps":"5","rpe_target":7.5,"rest_seconds":180,"description":"Stand centered in the bar. Sit back and down to the handles. Explosive concentric — think about pushing the floor away as fast as possible."},{"movement_id":"box_jump","name":"Box Jump","sets":4,"reps":"5","rpe_target":7,"rest_seconds":120,"description":"Load hips before jumping — do not just dip and flop. Full extension at the top of the jump. Step down to protect the Achilles. Reset fully between reps."}]'::jsonb,
'[{"movement_id":"jump_squat","name":"Jump Squat","sets":3,"reps":"6","rpe_target":7,"rest_seconds":90,"description":"Bodyweight or very light load only. Quarter squat depth. Explode through full hip and knee extension. Land softly and immediately reload for the next rep."},{"movement_id":"single_leg_rdl","name":"Single-Leg RDL","sets":3,"reps":"8 each leg","rpe_target":6.5,"rest_seconds":90,"description":"Posterior chain balance work. Light load focused on hip stability and hamstring loading position."}]'::jsonb),

('athx_explosive_w1d2','athx','explosive_power',1,2,'Explosive — Hang Variations and Upper Power',
'Day 2 introduces the hang power snatch and builds upper body pulling power. ATHX athletes need pulling strength and upper body power that most hybrid athletes are missing entirely.',
'["3 min easy row","2x5 hang power clean empty bar","2x5 hang power snatch empty bar","Thoracic extension over foam roller 60 seconds","2x10 banded pull-apart"]'::jsonb,
'[{"movement_id":"hang_power_clean","name":"Hang Power Clean","sets":4,"reps":"4","rpe_target":7,"rest_seconds":150,"description":"Mid-thigh start. Push hips back then drive forward violently. Elbows snap through fast. Catch in a balanced athletic position."},{"movement_id":"hang_power_snatch","name":"Hang Power Snatch","sets":4,"reps":"4","rpe_target":7,"rest_seconds":150,"description":"Wide grip. Start at mid-thigh. Violent hip extension and shrug then punch overhead. Full lockout. This will be lighter than you expect — that is correct."},{"movement_id":"pendlay_row","name":"Pendlay Row","sets":4,"reps":"6","rpe_target":7.5,"rest_seconds":150,"description":"Horizontal torso. Bar starts on floor each rep. Explosive pull to lower chest. The dead stop between reps is what makes this exercise work."}]'::jsonb,
'[{"movement_id":"weighted_pullup","name":"Weighted Pull-Up","sets":3,"reps":"5","rpe_target":7.5,"rest_seconds":120,"description":"Dead hang start. Pull explosively — this is a power day so the concentric should be as fast as possible. Control the descent."},{"movement_id":"face_pull","name":"Face Pull","sets":3,"reps":"15","rpe_target":5.5,"rest_seconds":60,"description":"Shoulder health work. External rotation at end range. Light load, high control."}]'::jsonb);

-- ============================================================
-- CHAT SEED MESSAGES
-- Uses session_replication_role = replica to bypass FK checks so
-- coach messages can be seeded without a real auth.users entry.
-- This is the standard Supabase seed pattern for reference data.
-- ============================================================

-- Temporarily disable FK constraint enforcement for seed inserts
set session_replication_role = replica;

-- Sled & Loaded Carry track chat
insert into chat_messages (subtrack, user_id, author_name, content, is_coach, is_pinned, created_at) values
('sled_carry_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','Welcome to the Sled & Loaded Carry track. This 5-week cycle is going to build the hip drive and carry strength that directly translates to your Hyrox race. Ask questions here any time — I check this daily.',true,true,now() - interval '6 days'),
('sled_carry_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','That is completely normal. The safety bar demands more upper back engagement than a straight bar. It will click by Week 2.',true,false,now() - interval '5 days'),
('sled_carry_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','No straps for this programming. The grip demand is part of the stimulus. If your grip fails well before your legs do, that is important information — grip is a limiter in your Hyrox race.',true,false,now() - interval '4 days'),
('sled_carry_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','That is exactly the right kind of soreness. Most people underactivate glutes in their primary training. This track is waking them up. It should ease up by Week 3.',true,false,now() - interval '20 hours');

-- Overhead Shoulder Strength track chat
insert into chat_messages (subtrack, user_id, author_name, content, is_coach, is_pinned, created_at) values
('overhead_shoulder_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','Overhead track is live. This cycle will build the pressing and pulling strength that makes gymnastics movements feel easier. Z-Press is going to be your best friend and worst enemy simultaneously.',true,true,now() - interval '6 days'),
('overhead_shoulder_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','An empty bar Z-Press done well is more valuable than 95 lbs done with a collapsing torso. Start lighter than you think you need to.',true,false,now() - interval '5 days'),
('overhead_shoulder_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','Schedule this track either on a rest day or at minimum 6 hours after your WOD. The pull-up work needs you fresh enough to actually add load.',true,false,now() - interval '4 days'),
('overhead_shoulder_strength','00000000-0000-0000-0000-000000000001','Coach Marcus','If the strict press is consistently uncomfortable on one side let me know. We can program more landmine work and less strict press for you this cycle.',true,false,now() - interval '2 days');

-- ATHX Explosive Power track chat
insert into chat_messages (subtrack, user_id, author_name, content, is_coach, is_pinned, created_at) values
('explosive_power','00000000-0000-0000-0000-000000000001','Coach Marcus','ATHX Explosive Power track is open. This 6-week cycle builds the rate of force development you need for every explosive demand in ATHX competition. Do not chase load on the Olympic lifting variations — speed is the goal.',true,true,now() - interval '6 days'),
('explosive_power','00000000-0000-0000-0000-000000000001','Coach Marcus','Try thinking elbows to the wall in front of you as you catch. Also check that you are not catching too far back on your heels — a slightly forward catch position allows faster elbow turnover.',true,false,now() - interval '5 days'),
('explosive_power','00000000-0000-0000-0000-000000000001','Coach Marcus','Focus on keeping the bar close to your body all the way through the pull before it goes overhead. Drop the load 20% and film yourself from the side.',true,false,now() - interval '4 days'),
('explosive_power','00000000-0000-0000-0000-000000000001','Coach Marcus','That sequencing is intentional — in ATHX you need to produce power when fatigued. But in Week 1 if the jump quality is really degraded by the last set it is okay to end a rep or two early.',true,false,now() - interval '2 days');

-- Re-enable FK constraint enforcement
set session_replication_role = default;
